#!/bin/sh

/usr/bin/CFControl --spt=30 --stt=60 --speed=25
/usr/bin/CFControl --spt=40 --stt=60 --speed=35
/usr/bin/CFControl --spt=50 --stt=60 --speed=50
/usr/bin/CFControl --spt=60 --stt=60 --speed=65
/usr/bin/CFControl --spt=70 --stt=60 --speed=75
/usr/bin/CFControl --spt=80 --stt=60 --speed=100


